# Numpy array

1. main purpose of numpy arrays is for mathematical calculation large amount of data

In [1]:
import numpy as np 

In [2]:
a1=np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [3]:
# to check dimension of the array 

a1.ndim

1

In [4]:
a1.shape 

(6,)

In [5]:
type(a1)

numpy.ndarray

In [6]:
b=[2,21,5,6,78,9]
b

[2, 21, 5, 6, 78, 9]

In [7]:
type(b)

list

In [8]:
c= np.array(b)
c

array([ 2, 21,  5,  6, 78,  9])

In [9]:
type(b)

list

In [10]:
type(c)

numpy.ndarray

In [11]:
d=[[1,2,3,4,5],
   [6,7,8,9,0]]
d

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

In [12]:
type(d)

list

In [13]:
h= np.array(d)

In [14]:
h

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [15]:
type(h)

numpy.ndarray

In [17]:
h.shape

(2, 5)

In [19]:
h.ndim

2

In [22]:
e=[[[1,2,3,4],
    [5,6,7,8]],
    
    [[11,12,13,14],
     [15,16,17,18]],
     
     [[22,34,56,78],
      [78,89,76,54]]]
type(e)

list

In [23]:
e1=np.array(e)
e1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18]],

       [[22, 34, 56, 78],
        [78, 89, 76, 54]]])

In [25]:
g=[1,2,3,4,5]
type(g)

list

In [26]:
g1=[]
for i in g:
    g1.append(i*3)

In [27]:
g1

[3, 6, 9, 12, 15]

In [28]:
a=np.array(g)
a

array([1, 2, 3, 4, 5])

In [29]:
j=3*a

In [30]:
j

array([ 3,  6,  9, 12, 15])

In [31]:
m= 2.5* h + h* 5
m

array([[ 7.5, 15. , 22.5, 30. , 37.5],
       [45. , 52.5, 60. , 67.5,  0. ]])

In [32]:
a = [4, 5, 6, 7]
type(a)

list

In [33]:
p= 1
for i in a:
    p= p*i

In [34]:
p

840

In [35]:
np.prod(a)

np.int64(840)

In [36]:
np.mean(a)

np.float64(5.5)

In [37]:
np.sum(a)

np.int64(22)

In [39]:
b=[[2,3,4,5],
   [6,7,8,9],
   [12,3,4,6]]

In [40]:
np.sum(b)

np.int64(69)

In [41]:
np.prod(b)

np.int64(313528320)

In [42]:
np.sum(b,axis=0)

array([20, 13, 16, 20])

In [43]:
np.sum(b, axis=1)

array([14, 30, 25])

In [44]:
np.mean(b)

np.float64(5.75)

In [45]:
np.average(b, axis=1)

array([3.5 , 7.5 , 6.25])

# Range function

range(start,stop,step)